<?php

namespace SkinnyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UlImgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UlImgRepository extends EntityRepository
{
}
