account_index:
    path:     /
    defaults: { _controller: "SkinnyBundle:Account:index" }
    methods:  GET

account_show:
    path:     /{id}/show
    defaults: { _controller: "SkinnyBundle:Account:show" }
    methods:  GET

account_new:
    path:     /new
    defaults: { _controller: "SkinnyBundle:Account:new" }
    methods:  [GET, POST]

account_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkinnyBundle:Account:edit" }
    methods:  [GET, POST]

account_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkinnyBundle:Account:delete" }
    methods:  DELETE
