accueil_index:
    path:     /
    defaults: { _controller: "SkinnyBundle:Accueil:index" }
    methods:  GET

accueil_show:
    path:     /{id}/show
    defaults: { _controller: "SkinnyBundle:Accueil:show" }
    methods:  GET

accueil_new:
    path:     /new
    defaults: { _controller: "SkinnyBundle:Accueil:new" }
    methods:  [GET, POST]

accueil_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkinnyBundle:Accueil:edit" }
    methods:  [GET, POST]

accueil_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkinnyBundle:Accueil:delete" }
    methods:  DELETE
